# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.postgres_user %>
  password: <%= Rails.application.credentials.postgres_password %>

development:
  <<: *default
  database: librarydev
  host: localhost
  port: 5432

test:
  <<: *default
  database: librarytest
  host: localhost
  port: 5432

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
